version: "3.8"

services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432

  climate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - HTTP_PORT=${HTTP_PORT}
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
  media: