CREATE TABLE IF NOT EXISTS categories(
    id SERIAL NOT NULL PRIMARY KEY,
    category_name VARCHAR(60) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP WITHOUT TIME ZONE
);